import asyncio
import time
import os
import requests
import streamlit as st
import inngest

# -------------------------------
# CONFIG
# -------------------------------
def get_secret(key, default=None):
    try:
        return st.secrets[key]
    except Exception:
        return os.getenv(key, default)

INNGEST_EVENT_KEY = get_secret("INNGEST_EVENT_KEY","uTah3eSR2Mi5RA0oBI4EmfLj34qO-Wk0Q0XCJyQaZ3ExMXDCMOfQ3R-4qFO4NuJGOo5ZsSkWzWOsTJPnl7t8FQ") 
INNGEST_REST_API_KEY = get_secret("INNGEST_REST_API_KEY","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6OTk1NmE2OGYtZTQ3ZC00ZWI5LWJmZDctMDdhYmMyZjllMTZkIn0.6jqqm-GcYlt3uAe88tHvQSTSpSTjKguR_XCx3LvaYOU") 
INNGEST_API_BASE = get_secret("INNGEST_API_BASE", "https://api.inngest.com/v1")
FASTAPI_URL = get_secret("FASTAPI_URL","https://pdfreaderaiagent.onrender.com")

# -------------------------------
# STREAMLIT SETUP
# -------------------------------
st.set_page_config(page_title="RAG PDF App", page_icon="📄")

# -------------------------------
# INNGEST CLIENT
# -------------------------------
@st.cache_resource
def get_client():
    if not INNGEST_EVENT_KEY:
        raise ValueError("❌ Missing INNGEST_EVENT_KEY")

    return inngest.Inngest(
        app_id="rag_app",
        event_key=INNGEST_EVENT_KEY,
        is_production=True,
    )

# -------------------------------
# UPLOAD FILE TO FASTAPI
# -------------------------------
def upload_to_backend(file):
    files = {"file": (file.name, file.getvalue(), "application/pdf")}
    response = requests.post(f"{FASTAPI_URL}/api/upload", files=files)

    st.write("STATUS:", response.status_code)
    st.write("RESPONSE:", response.text)

    response.raise_for_status()

    data = response.json()

    return data["file_path"], data["filename"]

# -------------------------------
# SEND INGEST EVENT
# -------------------------------
async def send_ingest(file_path, filename):
    client = get_client()

    result = await client.send(
        inngest.Event(
            name="rag/ingest_pdf",
            data={
                "pdf_path": file_path,
                "source_id": filename,
            },
        )
    )

    return result[0]

# -------------------------------
# SEND QUERY EVENT
# -------------------------------
async def send_query(question, top_k):
    client = get_client()

    result = await client.send(
        inngest.Event(
            name="rag/query_pdf_ai",
            data={
                "question": question,
                "top_k": top_k,
            },
        )
    )

    return result[0]

# -------------------------------
# UI - UPLOAD SECTION
# -------------------------------
st.title("📄 PDF RAG System")

file = st.file_uploader("Upload PDF", type=["pdf"])

if file:
    with st.spinner("Uploading file..."):
        file_path, filename = upload_to_backend(file)

    with st.spinner("Sending ingestion event..."):
        event_id = asyncio.run(send_ingest(file_path, filename))

    st.success("✅ PDF sent for processing")
    st.info(f"Event ID: {event_id}")

# -------------------------------
# UI - QUESTION SECTION
# -------------------------------
st.divider()
st.title("💬 Ask Questions")

question = st.text_input("Ask something about your PDFs")
top_k = st.number_input("Top K", min_value=1, max_value=10, value=5)

if st.button("Ask") and question.strip():
    with st.spinner("Sending query to AI..."):
        event_id = asyncio.run(send_query(question.strip(), int(top_k)))

    st.success("✅ Query sent to Inngest")
    st.info("💡 Answer will be generated by backend automatically")
    st.code(f"Event ID: {event_id}")